/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as src from "./src";
export type { src };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { ArtistFundManager } from "./src/contracts/base/ArtistFundManager";
export { ArtistFundManager__factory } from "./factories/src/contracts/base/ArtistFundManager__factory";
